# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 12:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.FileField(null=True, upload_to='images/')),
                ('cover_letter', models.TextField()),
                ('language', models.CharField(max_length=200)),
                ('frameworke', models.CharField(max_length=200)),
                ('frontend_technology', models.CharField(max_length=200)),
                ('data_base', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=200)),
                ('Datetime', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 4, 12, 13, 0, 514323))),
            ],
        ),
    ]
