# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 12:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 4, 12, 16, 1, 51927)),
        ),
    ]
