# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0003_remove_technology_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='expirence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=80, null=True)),
                ('frameworke', models.CharField(max_length=200)),
                ('frontend_technology', models.CharField(max_length=200)),
                ('data_base', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='technology',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 4, 13, 58, 34, 30562)),
        ),
    ]
