# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0004_auto_20190104_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirence',
            name='frameworke',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 4, 14, 3, 24, 702457)),
        ),
    ]
