# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0005_auto_20190104_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='devsign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('gmail', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='technology',
        ),
    ]
