# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0007_auto_20190108_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='frameworke',
            new_name='framework',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='language',
            new_name='other_skills',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='other',
            new_name='programing_language',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='java',
        ),
        migrations.AddField(
            model_name='technology',
            name='devlopment_tools',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='operrating_system',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
