# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0008_auto_20190109_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='devlopment_tools',
            new_name='development_tools',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='operrating_system',
            new_name='operating_system',
        ),
        migrations.AddField(
            model_name='technology',
            name='expirence',
            field=models.IntegerField(null=True),
        ),
    ]
