# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0009_auto_20190109_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.FileField(null=True, upload_to='images/')),
                ('Datetime', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 9, 12, 0, 3, 59418))),
                ('cover', models.TextField()),
                ('Designation', models.CharField(max_length=100)),
                ('complete_project', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='technology',
            name='expirence',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
