# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0010_auto_20190109_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='salary',
            new_name='salary_year',
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_hour',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_month',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 10, 7, 20, 0, 581172)),
        ),
    ]
