# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0011_auto_20190110_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='expirence',
            new_name='expirencedb',
        ),
        migrations.AddField(
            model_name='technology',
            name='expirenceft',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='expirencefw',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='expirenceos',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='expirencepl',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 10, 12, 43, 51, 658669)),
        ),
    ]
