# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0012_auto_20190110_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevloperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Required a valid email address.', max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Exep',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 11, 7, 21, 13, 24370)),
        ),
    ]
