# Generated by Django 2.1.5 on 2019-01-16 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0021_auto_20190116_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 16, 12, 24, 49, 243829)),
        ),
    ]
