# Generated by Django 2.1.5 on 2019-01-16 13:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0023_auto_20190116_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 16, 13, 10, 20, 479657)),
        ),
        migrations.AlterField(
            model_name='technology',
            name='usertech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
