# Generated by Django 2.1.5 on 2019-01-17 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0024_auto_20190116_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 17, 5, 44, 28, 23886)),
        ),
    ]
