# Generated by Django 2.1.5 on 2019-01-17 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0025_auto_20190117_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='usertech',
            new_name='user_tech',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 17, 5, 49, 34, 771396)),
        ),
    ]
