# Generated by Django 2.1.5 on 2019-01-21 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0026_auto_20190117_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 21, 11, 11, 21, 728847)),
        ),
        migrations.AlterField(
            model_name='technology',
            name='expirencedb',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='expirenceft',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='expirencefw',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='expirenceos',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='expirencepl',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
