# Generated by Django 2.1.5 on 2019-01-21 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0028_auto_20190121_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 21, 11, 56, 15, 981652)),
        ),
    ]
