# Generated by Django 2.1.5 on 2019-01-22 12:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('YouTeamapp', '0035_auto_20190122_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='devlopertechnical',
            fields=[
                ('programing_language', models.CharField(max_length=100)),
                ('user_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('expirencepl', models.CharField(max_length=3, null=True)),
                ('framework', models.CharField(max_length=200)),
                ('expirencefw', models.CharField(max_length=3, null=True)),
                ('frontend_technology', models.CharField(max_length=200)),
                ('expirenceft', models.CharField(max_length=3, null=True)),
                ('data_base', models.CharField(max_length=200)),
                ('expirencedb', models.CharField(max_length=3, null=True)),
                ('other_skills', models.CharField(max_length=200)),
                ('expirenceos', models.CharField(max_length=3, null=True)),
                ('development_tools', models.CharField(max_length=200, null=True)),
                ('operating_system', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expirence',
            name='user_tech',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 22, 12, 15, 3, 29895)),
        ),
        migrations.DeleteModel(
            name='Expirence',
        ),
    ]
