# Generated by Django 2.1.5 on 2019-01-24 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0038_auto_20190124_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 24, 11, 44, 30, 590761)),
        ),
    ]
