# Generated by Django 2.1.5 on 2019-01-24 13:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('YouTeamapp', '0040_auto_20190124_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='devoloperprofile',
            fields=[
                ('Pic', models.FileField(null=True, upload_to='images/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Datetime', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 24, 13, 10, 21, 203245))),
                ('Designation', models.CharField(max_length=100)),
                ('complete_project', models.CharField(max_length=100)),
                ('salary_year', models.FloatField(null=True)),
                ('salary_month', models.FloatField(null=True)),
                ('salary_hour', models.FloatField(null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('Zip_code', models.CharField(max_length=10, null=True)),
                ('offical_email', models.CharField(max_length=80)),
                ('LinkedIn_profile_url', models.CharField(max_length=100, null=True)),
                ('cover', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='devloperprofile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='customer',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
