# Generated by Django 2.1.5 on 2019-01-30 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0041_auto_20190124_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='devoloperprofile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 30, 7, 23, 26, 547529)),
        ),
    ]
