# Generated by Django 2.1.5 on 2019-01-30 09:46

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YouTeamapp', '0045_auto_20190130_0944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='free',
            new_name='freeall',
        ),
        migrations.AlterField(
            model_name='devoloperprofile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 30, 9, 46, 2, 638961)),
        ),
    ]
