# Generated by Django 2.1.5 on 2019-02-06 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0046_auto_20190130_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='freeall',
            name='user',
        ),
        migrations.AlterField(
            model_name='devoloperprofile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 6, 10, 51, 6, 695795)),
        ),
        migrations.DeleteModel(
            name='freeall',
        ),
    ]
