# Generated by Django 2.1.5 on 2019-02-07 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0047_auto_20190206_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empolyee_name', models.CharField(max_length=50)),
                ('Compny_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='usersignup',
        ),
        migrations.AlterField(
            model_name='devoloperprofile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 7, 7, 58, 54, 830332)),
        ),
    ]
