# Generated by Django 2.1.5 on 2019-02-07 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTeamapp', '0048_auto_20190207_0758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Free',
            new_name='Freemodel',
        ),
        migrations.AlterField(
            model_name='devoloperprofile',
            name='Datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 7, 8, 3, 30, 19837)),
        ),
    ]
